const fs=require("fs"),d="/Users/devlindorvilma/projet-ia/agent-system/backend/src/agents/handlers/",b=fs.readFileSync(d+"BackendDevHandler.ts","utf8");
const configs=[
["FrontendDevHandler","FRONTEND_DEV","Frontend Developer","component_analyzer","Frontend component structure and rendering analysis for","Extract reusable UI primitives into a shared component library to reduce duplication","Implement React.memo and useMemo for expensive render paths to prevent unnecessary re-renders","Add comprehensive prop validation with TypeScript interfaces and runtime boundary checks"],
["DevOpsHandler","DEVOPS","DevOps Engineer","infrastructure_analyzer","Infrastructure topology and deployment pipeline analysis for","Adopt infrastructure-as-code with Terraform modules to ensure reproducible environment provisioning","Implement blue-green deployments with automated rollback triggers based on health check failures","Add container resource limits and horizontal pod autoscaling policies to handle traffic spikes"],
["QAHandler","QA","QA Engineer","test_runner","Test coverage and quality assurance evaluation for","Increase branch coverage to 80% minimum by adding edge-case unit tests for error handling paths","Introduce integration tests with database fixtures to validate end-to-end data flow correctness","Set up regression test suites triggered on every pull request to catch breaking changes early"],
["SecurityHandler","SECURITY","Security Engineer","security_scanner","Vulnerability assessment and threat modeling analysis for","Enforce parameterized queries across all database interactions to eliminate SQL injection vectors","Implement strict Content-Security-Policy headers and sanitize all user-generated content outputs","Rotate secrets via a centralized vault with short-lived tokens and audit access logs regularly"],
["DataEngineerHandler","DATA_ENGINEER","Data Engineer","pipeline_analyzer","Data pipeline integrity and transformation logic review for","Add schema validation checkpoints between pipeline stages to catch data drift before it propagates","Implement idempotent write operations with deduplication keys to guarantee exactly-once processing","Partition large datasets by time-based keys and add incremental processing to reduce batch latency"],
["PerformanceHandler","PERFORMANCE","Performance Specialist","profiler","Runtime profiling and resource utilization bottleneck analysis for","Introduce multi-layer caching with Redis for hot paths and CDN edge caching for static assets","Optimize critical database queries by adding composite indexes and eliminating N+1 fetch patterns","Implement lazy loading and code splitting to reduce initial bundle size and time-to-interactive"],
["DocumentationHandler","DOCUMENTATION","Documentation Writer","doc_generator","Documentation completeness and clarity audit for","Generate API reference docs from TypeScript types with usage examples for every public endpoint","Add architecture decision records (ADRs) to capture the rationale behind major design choices","Create onboarding runbooks with step-by-step local setup and troubleshooting guides"],
["ProductManagerHandler","PRODUCT_MANAGER","Product Manager","requirement_analyzer","Requirements validation and user story completeness assessment for","Define clear acceptance criteria with measurable outcomes for each user story before development starts","Prioritize features using a weighted impact-effort matrix aligned with quarterly business objectives","Establish feedback loops with stakeholders through structured demo sessions after each sprint cycle"],
["SolutionsArchitectHandler","SOLUTIONS_ARCHITECT","Solutions Architect","system_designer","System design evaluation and architectural pattern review for","Decompose monolithic services into bounded contexts with well-defined API contracts between domains","Introduce an event-driven architecture with a message broker to decouple service dependencies","Design for horizontal scalability by ensuring stateless services and externalizing session state"],
["TechLeadHandler","TECH_LEAD","Technical Lead","code_reviewer","Code quality assessment and engineering standards compliance review for","Enforce consistent coding standards with automated linting rules and pre-commit hooks across the team","Reduce cyclomatic complexity by extracting shared logic into well-tested utility functions","Adopt conventional commits and semantic versioning to maintain a clear and traceable changelog"]
];
for(const c of configs){let t=b;t=t.replace(/BackendDevHandler/g,c[0]);t=t.replace(/BACKEND_DEV/g,c[1]);
t=t.replace(/Backend Developer/g,c[2]);t=t.replace(/code_generation/g,c[3]);
t=t.replace(/Analyzed backend task/g,c[4]);
t=t.replace(/Follow REST conventions/g,c[5]);t=t.replace(/Add input validation/g,c[6]);t=t.replace(/Include error handling/g,c[7]);
t=t.replace(/codeStructure: task.input/g,'output: task.input');
t=t.replace(/    \/\/ Record tool invocation
/g,'');t=t.replace(/    \/\/ Agent processes the task.*
/g,'');
fs.writeFileSync(d+c[0]+".ts",t);console.log("Created "+c[0]+".ts");}
